# src/OC/PlatformBundle/Resources/config/routing.yml

oc_platform_home:
    path:      /platform
    defaults: {_controller: OCPlatformBundle:Advert:index}

oc_platform_view:
    path:      /platform/advert/{id}
    defaults: {_controller: OCPlatformBundle:Advert:view}

oc_platform_add:
    path:      /platform/add
    defaults: {_controller: OCPlatformBundle:Advert:add}



# src/OC/PlatformBundle/Resources/config/routing.yml

oc_platform_view_slug:
    path:      /platform/{year}/{slug}.{format}
    defaults:
        _controller: OCPlatformBundle:Advert:viewSlug
        format:      html      #cette ligne permet de mettre un valeur par defaut à format, ici c'est html
    requirements:
        year:    \d{4}      #le \d{4} veux dire 4 chiffres à la suite
        format: html|xml